---
- name: Add Filesystems repo
  become: true
  community.general.zypper_repository:
    repo: "https://download.opensuse.org/repositories/filesystems/{{ ansible_distribution_version }}/filesystems.repo"
    state: present

- name: Install packages
  become: true
  community.general.zypper:
    name: "{{ openzfs_packages }}"
    state: present
    update_cache: true

...
