---
- name: Add universe repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe
    state: present

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ openzfs_packages }}"
    state: present
    update_cache: true

...
